version: '3.5'
services:
  grafana:
    build: .
    volumes:
      - ./grafana-conf/:/etc/grafana/
    ports:
      - 3000:3000
    networks:
      net:
  
  nginx:
    image: nginx:latest
    hostname: nginx
    volumes:
      - /var/www/html/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      net:

networks:
  net:
    driver: bridge
